#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Acknowledge the v4 to v5 migration notice raised by bin/module-migrate-v5
#

import agent

agent.unset_env("DT_MIGRATION_NOTICE")
