#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# If the control reaches this step, the service can be enabled and started

touch smarthost.env

systemctl --user enable \
    postgresql-app.service \
    dependencytrack-apiserver.service \
    trivy-app.service \
    dependencytrack-frontend.service

systemctl --user restart \
    postgresql-app.service \
    dependencytrack-apiserver.service \
    trivy-app.service \
    dependencytrack-frontend.service
