#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


set -e 

/usr/bin/mkdir -vp nginx

cat >nginx/default.conf <<'EOF'
server {
  listen 80;

  server_name _;

  ### DEPENDENCY TRACK FRONTEND
  location / {
    proxy_pass http://127.0.0.1:8081/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_hide_header X-Powered-By;
    proxy_hide_header Server;
  }

  ### DEPENDENCY TRACK APISERVER
  location /api/ {
    proxy_pass http://127.0.0.1:8080/api/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_hide_header X-Powered-By;
    proxy_hide_header Server;

  }
}
EOF

cat >nginx/default.conf.template <<'EOF'
server {
  listen      8081;
  listen  [::]:8081;
  server_name _;

  location / {
    root      /opt/owasp/dependency-track-frontend;
    index     index.html;
    try_files $uri $uri/ /index.html;

    location ~ (config\.json|index\.html)$ {
      add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
      add_header Pragma "no-cache";
      add_header Expires 0;
    }

    sub_filter '<base href=/'  '<base href=${BASE_PATH}';
    sub_filter_once on;
  }

  error_page 500 502 503 504 /50x.html;

  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
EOF