#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

mkdir -vp restore
cat - >restore/dependencytrack_restore.sh <<'EOS'
# Read dump file from standard input:
pg_restore --no-owner --no-privileges -U postgres -d dependencytrack
ec=$?
docker_temp_server_stop
exit $ec
EOS

# read secrets.env and set the variable POSTGRES_TOKEN
POSTGRES_TOKEN=$(grep -E '^POSTGRES_TOKEN=' secrets.env | cut -d= -f2-)
if [[ -z "$POSTGRES_TOKEN" ]]; then
    echo "Cannot restore: POSTGRES_TOKEN is not set in secrets.env"
    exit 1
fi

podman run \
    --rm \
    --interactive \
    --network=none \
    --volume=./restore:/docker-entrypoint-initdb.d/:Z \
    --volume=postgres-data:/var/lib/postgresql/data:Z \
    --replace --name=restore_db \
    --env POSTGRES_USER=postgres \
    --env POSTGRES_PASSWORD=${POSTGRES_TOKEN} \
    --env POSTGRES_DB=dependencytrack \
    --env TZ=UTC \
    "${POSTGRES_IMAGE}" < dependencytrack.pg_dump

# If the restore is successful, clean up:
rm -rfv restore/ dependencytrack.pg_dump
